### ISSUE TITLE
launch Wiki Unblocked

### ISSUE THREAD

**Issue by eighthave** [greatfire/apps-android-wikipedia-envoy#1]
> I think we are good to go with the following guidelines for Wikipedia. Let me know if you have any questions.  We reviewed the Wikimedia guidelines on use of Wikipedia content. Our plan is to release an Android app which would:

- [x]  be called "Wiki Unblocked" (this will be translated into the local language) - or called any other name, but cannot include "Wikipedia" or "Wikimedia"
- [x] create a logo we will use for the app (we do not use any Wikimedia visual property) 
- [x] once users open the app, they will be directed to the local language versions of the Wikipedia home pages
- [x] users will then be able to navigate the Wikipedia site as they normally would
- [ ] GF signs it

@mnbogner @stevenmcdonald

**Comment by mnbogner** [comment]
regarding the 3rd item, do you want to prompt the user to select a language at startup or select the language automatically based on the language settings of the device?  currently it seems like the ui language will reflect the language on the device, but the language for the articles must be manually selected from the configuration menu.

**Comment by mnbogner** [comment]
when testing today i was reminded that the app will prompt the user to select a language the first time it runs, so unless you'd rather try to make it automatically detect the language the 3rd item may already be satisfied.

**Comment by eighthave** [comment]
I think it makes the most sense to automatically select the default language 
based on the device settings.  The target audience is less likely to be 
comfortable in English.

**Comment by mnbogner** [comment]
to clarify, i think the text of the ui automatically reflects the device settings, but the app then prompts them (in their language) to select the language for the wiki articles.  this might be difficult to replace with automation since the wiki article language options didn't seem to correspond directly to device language options.  i'll try to collect some screenshots of the current behavior.

**Comment by mnbogner** [comment]
@eighthave i changed the application id but the "Wikipedia" app name has been translated across many languages.  Should I just replace it with "Wiki Unblocked" in english and wait for translations to be done later?

Also, I will replace the logos in the app, but I assume the content loaded from the site can still have wikipedia assets?

One final thing I will document here that we've already spoken of is that the original application id was tied to a number of google service ids for the different build flavors.  The app seems to run as intended when these are commented out but we may need to revisit this at some point.

**Comment by mnbogner** [comment]
Here are some screenshots of the current version showing the new name and logo, as well as the initial language choice screen.  I'd consider removing the logo from the upper left hand corner of the main screen.  I replaced an image of the text "Wikipedia" with the logo, but it doesn't look right to me.

![screen1_mark](https://user-images.githubusercontent.com/6945405/171968299-f7feba04-4cdb-4835-ad35-b87c7d8e2853.png)
![screen2](https://user-images.githubusercontent.com/6945405/171968304-b1ff5808-4609-4be0-ad26-ff5acef1089e.png)
![screen3](https://user-images.githubusercontent.com/6945405/171968310-991af144-2082-4441-a5bc-3bde060e0ea4.png)
![screen4_mark](https://user-images.githubusercontent.com/6945405/171968314-0d87a5b3-385d-4652-b93a-1c576ec456a2.png)
![screen5_mark](https://user-images.githubusercontent.com/6945405/171968316-8ddf95f4-8e50-49d0-a4f5-d81286ba072f.png)

**Comment by eighthave** [comment]
> @eighthave i changed the application id but the "Wikipedia" app name has been translated across many languages. Should I just replace it with "Wiki Unblocked" in english and wait for translations to be done later?

How about a `sed 's,Wikipedia,Wiki Unblocked,g'` on all of the _strings.xml_?

**Comment by mnbogner** [comment]
Unfortunately the strings files include a bunch of occurrences that can't be changed like URLs.  There are also occurrences that I'm not sure it makes sense to change, like "Log in to your Wikipedia account" (since there's no such thing as a Wiki Unblocked account).  Are there particular uses we're legally obligated to change?

**Comment by eighthave** [comment]
Leaving "wikipedia account" seems totally legit.  If something is actually referring to the Wikipedia site, it should stay that way.  This app is just a wrapper on the WMF sites.  So really, just the app name needs to be changed.  Looks like WMF's build system already includes a build flavor setup for doing this stuff, so here'a commit that sets up a `greatfire` build flavor:
https://github.com/eighthave/apps-android-wikipedia/commits/envoy-demo

That should cover the app name changes.  The icon needs to be added to:
* app/src/greatfire/res/mipmap-anydpi-v26/launcher.xml
* app/src/greatfire/res/mipmap-hdpi/launcher.png
* app/src/greatfire/res/mipmap-mdpi/launcher.png
* app/src/greatfire/res/mipmap-xhdpi/launcher.png
* app/src/greatfire/res/mipmap-xxhdpi/launcher.png
* app/src/greatfire/res/mipmap-xxxhdpi/launcher.png

**Comment by eighthave** [comment]
I just found your commits with the graphics and refactored into my branch so that the graphics are in the build flavor.  Then we don't have to modify those upstream files.  Once this works, we can release.  Going forward after that, I think it would make sense to move as many changes as possible into the build flavor.  That'll make maintenance a lot easier.

**Comment by eighthave** [comment]
I tried out https://github.com/mnbogner/apps-android-wikipedia/releases/tag/envoy-demo-v3. The icon, name, and Application ID is showing up correctly.  On a Nokia 3.1 running Android 10, it seems to work well.


I also installed it on an old Asus Nexus 7 2012 tablet running Android 7.1.2.  The official Wikipedia apps, but Wiki Unblocked quits pretty quickly with this crash:

```
                         E  Process: org.greatfire.wikiunblocked, PID: 27164
                         E  java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/app/Notification$Builder; or its super classes (declaration of 'android.app.Notification$Builder' appears in /system/framework/framework.jar)
                         E      at org.greatfire.envoy.ShadowsocksService.onStartCommand()
                         E      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
                         E      at android.app.ActivityThread.-wrap21(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6186)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

I tried it in an x86_64 emulator and got:

```
                         E  Process: org.greatfire.wikiunblocked, PID: 3937
                         E  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/base.apk"],nativeLibraryDirectories=[/data/app/org.greatfire.w
                            ikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64, /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libcronet.87.0.4280.
                            66.so"
                         E      at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
                         E      at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
                         E      at java.lang.System.loadLibrary(System.java:1667)
                         E      at org.chromium.net.impl.CronetLibraryLoader.ensureInitialized(CronetLibraryLoader.java:71)
                         E      at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:154)
                         E      at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
                         E      at org.chromium.net.CronetEngine$Builder.build(CronetEngine.java:319)
                         E      at org.greatfire.envoy.NetworkIntentService.handleActionSubmit(Unknown Source:54)
                         E      at org.greatfire.envoy.NetworkIntentService.handleActionSubmit$default(Unknown Source:6)
                         E      at org.greatfire.envoy.NetworkIntentService.onHandleIntent(Unknown Source:54)
                         E      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
                         E      at android.os.Handler.dispatchMessage(Handler.java:107)
                         E      at android.os.Looper.loop(Looper.java:214)
                         E      at android.os.HandlerThread.run(HandlerThread.java:67)
                  DEBUG  F  #00 pc 00000000000943f8  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+24) (BuildId: b5c6019a3b4ea61b5e9a2f56319b584e)
                         F  #01 pc 0000000000097146  /apex/com.android.runtime/lib64/bionic/libc.so (abort+182) (BuildId: b5c6019a3b4ea61b5e9a2f56319b584e)
                         F  #02 pc 0000000000212c96  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #03 pc 00000000002d0655  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #04 pc 00000000002b6135  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #05 pc 00000000002b5fb3  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #06 pc 00000000002cfa09  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #07 pc 00000000002cf9d3  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #08 pc 00000000002cf98c  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #09 pc 00000000002cf94f  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #10 pc 00000000000fcafa  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #11 pc 000000000010cc74  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #12 pc 00000000000abfd2  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #13 pc 000000000010fa02  /data/app/org.greatfire.wikiunblocked-G4mNzKsrG99Dkljnpj8tng==/lib/x86_64/libsslocal.so
                         F  #14 pc 000000000008a985  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+117) (BuildId: b5c6019a3b4ea61b5e9a2f56319b584e)
          EGL_emulation  D  eglMakeCurrent: 0x7e040a80ad00: ver 3 1 (tinfo 0x7e04578e17c0)
```

**Comment by eighthave** [comment]
@mnbogner is that first release signed by the official key already?

**Comment by mnbogner** [comment]
i will try to set up an emulator and reproduce that.  as to the key i had intentionally used a key that would expire soon for the pre-release builds, i should replace that with a proper key and do a v3.1 release

**Comment by mnbogner** [comment]
@eighthave can you provide any additional details for the x86_64 emulator you tried?  did it crash as soon as the app started?

**Comment by eighthave** [comment]
yes basically.  The app showed briefly, then it crashed before I could do anything

**Comment by mnbogner** [comment]
I believe the app has been launched, can this issue be closed?

**Comment by eighthave** [comment]
Yup:
* https://play.google.com/store/apps/details?id=org.greatfire.wikiunblocked
* https://gitlab.com/fdroid/rfp/-/issues/2197
