### ISSUE TITLE
Content not loading on the app

### ISSUE THREAD

**Issue by emilygf** [greatfire/apps-android-wikipedia-envoy#2]
Content on the Envoy-Wiki app is not loading 
- the homepage content (Today, Top read, Picture of the day, etc) doesn't appear
- search results don't appear
![Wiki1](https://user-images.githubusercontent.com/105190628/169753909-b9124c26-dbd8-4d9c-af5d-3ffd50555a34.jpg)
![Wiki2](https://user-images.githubusercontent.com/105190628/169753923-7a8e57fb-3241-4227-8c39-e13ce273cc90.jpg)
![Wiki3](https://user-images.githubusercontent.com/105190628/169753927-ffb9a97e-fece-424e-ad02-b59e42020505.jpg)

**Comment by emilygf** [comment]
I also tried to download the original wiki app from Google Play store after installing this Envoy-Wiki app. But, my phone was recognizing the Envoy-Wiki app as the original app. It didn't download the original app from the Play store, but instead kept opening the Envoy-Wiki app.

**Comment by mnbogner** [comment]
@emilygf if you have a moment, could you click on the "more" menu on the home page?  I added an icon at the bottom that should show whether a proxy is active or not and I wondered what that was showing.  You're running the newest release, correct? https://github.com/mnbogner/apps-android-wikipedia/releases/tag/envoy-demo-v2

![wiki](https://user-images.githubusercontent.com/6945405/169880565-383ded27-cdf2-42e5-86e2-3df2bed72f3b.png)

I didn't want to worry about translations yet so it should just show a check or an x next to the incognito icon.  Also, does any content appear if you swipe down to refresh?  At one point there was a timing issue where it would attempt to load content before the proxy was active but I thought I had fixed that.

**Comment by emilygf** [comment]
Oh I must have downloaded the old version I guess... I deleted the app and installed the demo v.2, and it works perfectly and fast now. Thanks!!
