### ISSUE TITLE
Envoy-Wiki vs. Original Wiki 

### ISSUE THREAD

**Issue by emilygf** [greatfire/apps-android-wikipedia-envoy#3]
I tried to download the original wiki app from Google Play store after installing this Envoy-Wiki app. But, my phone was recognizing the Envoy-Wiki app as the original app. It didn't download the original app from the Play store, but instead kept opening the Envoy-Wiki app.

**Comment by eighthave** [comment]
@mnbogner the Application ID needs to be changed to be something like `org.greatfire.wiki-unblocked`.

**Comment by emilygf** [comment]
This problem is solved now, thanks!

**Comment by mnbogner** [comment]
thanks, i think this issue still needs to be addressed

**Comment by eighthave** [comment]
this was fixed in envoy-demo-v3, the Application ID is now `org.greatfire.wikiunblocked` (`-` is not allowed in an Application ID.
