### ISSUE TITLE
get all libs from Maven Central

### ISSUE THREAD

**Issue by eighthave** [greatfire/apps-android-wikipedia-envoy#4]
- [ ] `implementation 'info.guardianproject.envoy:cronet:0.0.87.0.4280.66'`

- [ ] @mnbogner  is using this branch of envoy, so it should be published to Maven Central:  https://github.com/greatfire/envoy/commit/135fb8d86900879a9d37b042c8688c063aa2665d the 

- [ ]  last piece would be getting a maven dependency for the version of iptproxy with dnstt from @stevenmcdonald

**Comment by mnbogner** [comment]
Can this issue be resolved?  Currently cronet, envoy, and ienvoy proxy dependencies are all taken from maven for release builds:

https://github.com/mnbogner/apps-android-wikipedia/blob/v2ray/app/build.gradle#L347

**Comment by stevenmcdonald** [comment]
I think this is done
